# Generated by Django 5.2.4 on 2025-08-05 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='posts_post_user_id_b93466_idx'),
        ),
    ]
