# Generated by Django 5.2.4 on 2025-08-02 14:26

import accounts.AccountsUtils
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('profile_photo', models.ImageField(blank=True, default='profile_pics/default.webp', upload_to=accounts.AccountsUtils.profile_image_path)),
                ('cover_photo', models.ImageField(blank=True, default='cover_pics/default.webp', upload_to=accounts.AccountsUtils.cover_image_path)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
